# Generated by Django 4.2.10 on 2024-06-02 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collect', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collect',
            old_name='ear_injury',
            new_name='alopecia',
        ),
        migrations.RenameField(
            model_name='collect',
            old_name='observation_ear_injury',
            new_name='observation_alopecia',
        ),
        migrations.RemoveField(
            model_name='collect',
            name='lip_depigmentation',
        ),
        migrations.AddField(
            model_name='collect',
            name='age',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='collect',
            name='dna_strains',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='collect',
            name='lymph_node_aspirate_dna',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='collect',
            name='mucous_coloring',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='collect',
            name='observation_skin_injury',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='collect',
            name='strains',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
