# Generated by Django 4.2.10 on 2024-06-02 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collect', '0002_rename_ear_injury_collect_alopecia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collect',
            name='age',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='collect',
            name='alopecia',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='collect',
            name='animal',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='collect',
            name='biomanguinhos_elisa',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='collect',
            name='bleeding',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='collect',
            name='blepharitis',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='collect',
            name='conjunctivitis',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='collect',
            name='dilution',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='collect',
            name='dna_strains',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='collect',
            name='dt_collection',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='collect',
            name='ecto_paras',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='collect',
            name='fiocruz_elisa',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='collect',
            name='general_state',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='collect',
            name='latitude',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='collect',
            name='location_culture',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='collect',
            name='location_slide',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='collect',
            name='longitude',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='collect',
            name='lymph_node',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='collect',
            name='lymph_node_aspirate',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='collect',
            name='lymph_node_aspirate_dna',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='collect',
            name='marrow_aspirate',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='collect',
            name='mucous_coloring',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='collect',
            name='muzzle_depigmentation',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='collect',
            name='muzzle_injury',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='collect',
            name='nails',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='collect',
            name='nutritional_status',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='collect',
            name='observation',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='collect',
            name='observation_alopecia',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='collect',
            name='observation_conjuntivitis',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='collect',
            name='observation_lymph_node',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='collect',
            name='observation_muzzle_injury',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='collect',
            name='observation_skin_injury',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='collect',
            name='parasite_culture',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='collect',
            name='parasite_slide',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='collect',
            name='plasma',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='collect',
            name='score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='collect',
            name='serum',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='collect',
            name='skin_injury',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='collect',
            name='sorology_dpp',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='collect',
            name='sorology_rifi',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='collect',
            name='strains',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
