# Generated by Django 4.2.10 on 2024-06-02 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collect', '0003_alter_collect_age_alter_collect_alopecia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collect',
            name='coat',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
