# Generated by Django 4.2.10 on 2024-04-14 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0002_animal_caracteristics_animal_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='phone_number',
            field=models.CharField(max_length=15),
        ),
    ]
