# Generated by Django 4.2.10 on 2024-05-19 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coat', '0001_initial'),
        ('breed', '0002_breed_specie'),
        ('animal', '0003_alter_animal_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='age',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='animal',
            name='breed',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='breed.breed'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='caracteristics',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='animal',
            name='coat',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='coat.coat'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='id_db_original',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='animal',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='animal',
            name='name_chip',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='animal',
            name='owner',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='animal',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='animal',
            name='sex',
            field=models.CharField(blank=True, choices=[('F', 'Feminino'), ('M', 'Masculino')], max_length=1),
        ),
    ]
