# Generated by Django 4.2.10 on 2024-05-26 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0005_alter_animal_breed_alter_animal_coat_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='animal',
            options={'ordering': ('name',), 'verbose_name': 'Animal', 'verbose_name_plural': 'Animals'},
        ),
    ]
