# Generated by Django 4.2.10 on 2024-03-24 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('specie', '0001_initial'),
        ('breed', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='breed',
            name='specie',
            field=models.ForeignKey(default='59e10122aa4f4b718c3d1b06f907b26f', on_delete=django.db.models.deletion.CASCADE, to='specie.specie'),
        ),
    ]
