# Generated by Django 4.2.10 on 2024-05-26 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('breed', '0002_breed_specie'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='breed',
            options={'ordering': ('name',), 'verbose_name': 'Breed', 'verbose_name_plural': 'Breeds'},
        ),
    ]
